export const ItensFabri = [
    "carregadeira",
    "cabine gc",
    "compactador",
    "base compact",
    "cabine d5 / 7",
    "cabine d8",
    "plataforma d6",
    "plataforma 55",
    "oasis aberta",
    "oasis fechada",
    "cabine setra",
    "cabine 426",
    "dynapac",
    "cabine 422",
    "cabine 3cx",
    "cabine toldo",
    "romi",
    "enclosure 80/62",
    "enclosure t4",
]